name: Build APK

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
    secrets:
      KEY_PASSWORD:
        required: false
      STORE_PASSWORD:
        required: false
      OAUTH_CLIENT_ID:
        required: false
      CURSEFORGE_API_KEY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    env:
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      OAUTH_CLIENT_ID: 00000000402b5328
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          gradle-version: 8.13
          add-job-summary: "on-failure"

      - name: Build APK for ${{ matrix.arch }}
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assemble${{ inputs.variant }} -Darch=${{ matrix.arch }}

      - name: Upload Release APK for ${{ matrix.arch }}
        if: inputs.variant == 'Release'
        continue-on-error: true
        uses: actions/upload-artifact@main
        with:
          name: release apk (${{ matrix.arch }})
          path: ZalithLauncher/build/outputs/apk/release/*.apk