name: Android CI

on:
  workflow_dispatch: # 保留原有的手动触发功能
  schedule:
    # 北京时间(GMT+8)每天凌晨1点 对应 UTC时间 前一天17:00
    - cron: '0 17 * * *'

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      variant: Release
    secrets:
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      OAUTH_CLIENT_ID: 00000000402b5328
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}